
Vagrant.configure("2") do |config|
  
  config.vm.box = "openSUSE-42.1"
  config.vm.hostname = "vhcalnplci"
  config.vm.box_url = "./packer/openSUSE-42.1/openSUSE-42.1-virtualbox.box" 

   config.vm.network "forwarded_port", guest: 8000, host: 8000, id: "http", auto_correct: true
   config.vm.network "forwarded_port", guest: 44300, host: 44300, id: "https", auto_correct: true
   config.vm.network "forwarded_port", guest: 3300, host: 3300, id: "rfc", auto_correct: true
   config.vm.network "forwarded_port", guest: 3200, host: 3200, id: "sapgui", auto_correct: true
   config.vm.network "forwarded_port", guest: 22, host: 2222, id: "ssh", auto_correct: true
   

  
  config.vm.synced_folder "", "/vagrant", :owner => "vagrant"

 
   config.vm.provider "virtualbox" do |vb|
   
    vb.name = "SAPNetWeaver7.5SPS02"
    vb.gui = true
    vb.linked_clone = true

    
    vb.customize ["modifyvm", :id, "--memory", "8192", "--cpus", "2"]
    vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
    vb.customize ["modifyvm", :id, "--vram", "32"]
   end
  config.vm.provision "shell", path: "install/uuidd.sh"  
  config.vm.provision "shell", path: "install/sapinst.sh"

end
